[package]
name = "ch02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["cargo"] }
num = "0.4.1"
regex = "1.9.5"
