[package]
name = "ch07"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
crc = "3.0.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.105"
